/*ID_TERM, EXPENSE_CODE */

--GASTO DE VIATICOS
INSERT INTO EXPENSE_LIST
VALUES (2,'GDVTC'); 

--GASTO DE ESENOGRAFÍA
INSERT INTO EXPENSE_LIST
VALUES (2,'GDECN'); 

--GASTO DE ILUMINACIÓN
INSERT INTO EXPENSE_LIST
VALUES (2,'GDILM'); 