 /*ID_WORK_PL_STA, UNIT_CODE, EMPLOYEE_CODE, ID_STA_PLA_STAFF, ID_PLAY, ID_FUNCTION, ID_TERM, ACTIVITY_CODE */
                                                                        
INSERT INTO WORK_PLAY_STAFF (UNIT_CODE, EMPLOYEE_CODE, ID_STA_PLA_STAFF, ID_PLAY, ID_FUNCTION, ID_TERM, ACTIVITY_CODE) 
VALUES ('IGNST','SNOD',1,'RADJ',8,2,'DRTR1');                                                                                      

INSERT INTO WORK_PLAY_STAFF (UNIT_CODE, EMPLOYEE_CODE, ID_STA_PLA_STAFF, ID_PLAY, ID_FUNCTION, ID_TERM, ACTIVITY_CODE) 
VALUES ('IGNST','AJDZ',2,'RADJ',9,2,'CART1');   

INSERT INTO WORK_PLAY_STAFF (UNIT_CODE, EMPLOYEE_CODE, ID_STA_PLA_STAFF, ID_PLAY, ID_FUNCTION, ID_TERM, ACTIVITY_CODE) 
VALUES ('FCATS','RNQT',3,'RADJ',10,2,'AULA1');   